apiVersion: skaffold/v2beta26
kind: Config

build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
  artifacts:
    - image: api
      context: api

deploy:
  kubectl:
    manifests:
      - infra/api/*
