apiVersion: skaffold/v2beta26
kind: Config
build:
  tagPolicy:
    sha256: {}
  local:
    concurrency: 0
    useBuildkit: true
  artifacts:
    - image: api
      context: api2/server
    - image: migrator
      context: api2/migrator
deploy:
  kubectl:
    manifests:
      - infra/api/*
      - infra/migrator/*
      - infra/ingress.yaml
