apiVersion: batch/v1
kind: Job
metadata:
  name: seeder
spec:
  template:
    spec:
      containers:
        - name: seeder
          image: seeder:latest
          imagePullPolicy: Never
      restartPolicy: Never
